import type { Metadata } from "next";
import { Playfair_Display, Work_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Avena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={`${playfairDisplay.variable} ${workSans.variable} antialiased font-p`}
      >
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="avenal"
          enableSystem={true}
          themes={["avenal", "avenad"]}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
